- name: Install dependencies
  package:
    name:
      - dash
      - gcc
      - git
      - libxcb
      - libxcb-devel 
      - make
      - xcb-util 
      - xcb-util-devel
      - xcb-util-keysyms 
      - xcb-util-keysyms-devel 
      - xcb-util-wm 
      - xcb-util-wm-devel 

- block:
  - name: Clone bspwm
    become_user: cake
    git:
      repo: https://github.com/baskerville/bspwm.git
      dest: /opt/bspwm/
      clone: yes
      update: yes
      force: yes
  - name: Build bspwm
    become_user: cake
    make:
      chdir: /opt/bspwm/
  - name: Install bspwm
    make:
      chdir: /opt/bspwm/
      target: install
    register: result
    changed_when: result.stderr != ""

- block:
  - name: Clone sxhkd
    become_user: cake
    git:
      repo: https://github.com/baskerville/sxhkd.git
      dest: /opt/sxhkd/
      clone: yes
      update: yes
      force: yes
  - name: Build sxhkd
    become_user: cake
    make:
      chdir: /opt/sxhkd/
  - name: Install sxhkd
    make:
      chdir: /opt/sxhkd/
      target: install
    register: result
    changed_when: result.stderr != ""
