- name: Unassign switch-to-application hotkeys
  become_user: cake
  dconf:
    key: "/org/gnome/shell/keybindings/switch-to-application-{{item}}"
    value: "@as []"
  with_items: [1, 2, 3, 4, 5, 6, 7, 8, 9]

- name: Assign switch-to-application hotkeys
  become_user: cake
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-{{item}}"
    value: "['<Super>{{item}}']"
  with_items: [1, 2, 3, 4, 5, 6, 7, 8, 9]

- name: Configure Gnome
  include_role:
    name: petermosmans.customize-gnome
  vars:
    gnome_user: cake

    gnome_extensions:
      - id: 906 # Sound Input & Output Device Chooser
        enable: yes 
      - id: 1160 # Dash to Panel
        enable: yes 
      - id: 3193 # Blur my Shell
        enable: yes
      - id: 3843 # Just Perfection
        enable: yes
      - id: 5090 # Space Bar
        enable: yes

    gnome_gsettings:
      # shortcuts 
      - schema: org.gnome.settings-daemon.plugins.media-keys
        key: custom-keybindings
        value: >-
          "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

      # shortcut: terminal
      - schema: org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/
        key: name
        value: '"Launch Terminal"'
      - schema: org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/
        key: command
        value: alacritty
      - schema: org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/
        key: binding
        value: <Super>t
  
      # shortcut: rofi
      - schema: org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/
        key: name
        value: '"Launch Rofi"'
      - schema: org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/
        key: command
        value: '"rofi -show drun"'
      - schema: org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/
        key: binding
        value: <Control>Space

      # set default terminal
      - schema: org.gnome.desktop.default-applications.terminal 
        key: exec
        value: alacritty

      # enable EurKEY option
      - schema: org.gnome.desktop.input-sources
        key: show-all-sources
        value: '"true"'
      # set keyboard layout to EurKEY 
      - schema: org.gnome.desktop.input-sources
        key: sources
        value: '"[(''xkb'', ''eu'')]"'
      # remap caps to super
      - schema: org.gnome.desktop.input-sources
        key: xkb-options 
        value: '"[''caps:super'']"'

      # static workspaces
      - schema: org.gnome.mutter 
        key: dynamic-workspaces 
        value: '"false"'
      # amount of workspaces
      - schema: org.gnome.desktop.wm.preferences
        key: num-workspaces
        value: 9

    gnome_dconf:
      # super + number
      - key: /org/gnome/shell/extensions/space-bar/shortcuts/enable-activate-workspace-shortcuts
        value: '"false"'
      # super + shift + number
      - key: /org/gnome/shell/extensions/space-bar/shortcuts/enable-move-to-workspace-shortcuts
        value: '"true"'
      # multiple workspaces only on primary screen, secondary screens have 1 workspace
      - key: /org/gnome/mutter/workspaces-only-on-primary
        value: '"true"'

