- name: Add repository
  yum_repository:
    name: balena-etcher
    description: Balena Etcher
    baseurl: "https://dl.cloudsmith.io/public/balena/etcher/rpm/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}"
    gpgcheck: yes
    gpgkey: https://dl.cloudsmith.io/public/balena/etcher/gpg.70528471AFF9A051.key

- name: Install 
  package:
    name:
      - balena-etcher-electron
