- name: Repo cloning
  become_user: cake
  git:
    repo: git@github.com:kevincali/dotfiles.git
    dest: ~/git/dotfiles
    clone: yes
    update: yes
    force: yes

- name: Apply dotfiles
  become_user: cake
  command: chezmoi init --apply kevincali
  register: result
  changed_when: result.stderr != ""
