- block:
  - name: Chezmoi asdf plugin adding
    become_user: cake
    command: ~/.asdf/bin/asdf plugin-add chezmoi
    register: result
    failed_when: result.rc != 0 and result.rc != 2 not in result.stdout
    changed_when: False

  - name: Chezmoi asdf installation
    become_user: cake
    command: ~/.asdf/bin/asdf install chezmoi 2.31.1
    changed_when: False

  - name: Chezmoi asdf global configuration
    become_user: cake
    command: ~/.asdf/bin/asdf global chezmoi 2.31.1
    changed_when: False

- name: Repo cloning
  become_user: cake
  git:
    repo: git@github.com:kevincali/dotfiles.git
    dest: ~/git/dotfiles
    clone: yes
    update: yes
    force: yes

- name: Apply dotfiles
  become_user: cake
  command: chezmoi apply
  register: result
  changed_when: result.stderr != ""
