- name: Install interception tools dependencies
  package: 
    name:
      - cmake 
      - libevdev-devel 
      - systemd-devel 
      - yaml-cpp-devel 
      - boost-devel
- name: Interception tools cloning
  become_user: cake
  git:
    repo: https://gitlab.com/interception/linux/tools.git
    dest: /opt/interception-tools/
    clone: yes
    update: yes
- name: Interception tools installation
  shell: cmake -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build
  args:
    chdir: /opt/interception-tools/
  changed_when: False
- name: Copy interception-tools binaries to $PATH
  become_user: cake
  copy:
    src: "/opt/interception-tools/build/{{ item }}"
    dest: $HOME/.local/bin/
    mode: u+x
  with_items:
    - intercept
    - mux
    - udevmon
    - uinput

- name: Dual Function Keys cloning
  become_user: cake
  git:
    repo: https://gitlab.com/interception/linux/plugins/dual-function-keys.git
    dest: /opt/dual-function-keys/
    clone: yes
    update: yes
- name: Dual Function Keys installation Part 1
  become_user: cake
  make:
    chdir: /opt/dual-function-keys/
- name: Dual Function Keys installation Part 2
  make:
    chdir: /opt/dual-function-keys/
    target: install
  changed_when: False
