- name: Add repository
  yum_repository:
    name: keybase
    description: Keybase.io
    baseurl: http://prerelease.keybase.io/rpm/x86_64
    gpgcheck: yes
    gpgkey: https://keybase.io/docs/server_security/code_signing_key.asc

- name: Install 
  package:
    name:
      - keybase
