- name: Dependencies
  package:
    name:
      - ShellCheck
      - gcc-c++ 
      - proselint
      - python3-flake8
      - python3-isort
      - python3-lsp-black
      - tree-sitter-cli 

- name: Check if lvim is already installed
  become_user: cake
  command: which lvim
  register: lvim_installed
  changed_when: lvim_installed.stderr != ""
  ignore_errors: true

- name: Not Installed -> Installation
  become_user: cake
  shell: LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh) --overwrite --no-install-dependencies
  when: lvim_installed is failed
