- name: Dependencies
  package:
    name:
      - ShellCheck
      - gcc-c++ 
      - proselint
      - python3-flake8
      - python3-isort
      - python3-lsp-black
      - tree-sitter-cli 

- name: Check if lvim is already installed
  become_user: cake
  command: which lvim
  register: lvim_installed
  changed_when: lvim_installed.stderr != ""
  ignore_errors: true

- name: Not Installed -> Installation
  become_user: cake
  shell: LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh) --overwrite --no-install-dependencies 
  when: lvim_installed is failed
