- import_tasks: packages.yaml
  tags: [apps, packages]

- import_tasks: dotfiles.yaml
  tags: [apps, dotfiles]

- import_tasks: fish.yaml
  tags: [apps, fish]

- import_tasks: keybase.yaml
  tags: [apps, keybase]

- import_tasks: lvim.yaml
  tags: [apps, lvim]

- import_tasks: syncthing.yaml
  tags: [apps, syncthing]

- import_tasks: vscode.yaml
  tags: [apps, vscode]

- import_tasks: work.yaml
  tags: [apps, work]
  when: ansible_hostname == "work"
