- name: Pop Shell cloning
  become_user: cake
  git:
    repo: https://github.com/pop-os/shell.git
    dest: /opt/pop-shell/
    clone: yes
    update: yes
- name: Pop Shell installation
  become_user: cake
  make:
    chdir: /opt/pop-shell/
    target: "{{ item }}"
  with_items: [depcheck, compile, install, configure, enable] # removed restart-shell - might need to log out
  changed_when: False

- name: LunarVim installation
  become_user: cake
  shell: bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) --overwrite --no-install-dependencies 
  changed_when: False

- name: Lazygit cloning
  become_user: cake
  git:
    repo: https://github.com/jesseduffield/lazygit.git
    dest: /opt/lazygit/
    clone: yes
    update: yes
- name: Lazygit installation
  become_user: cake
  command: go install
  args:
    chdir: /opt/lazygit

- name: Enable Syncthing
  become_user: cake
  systemd:
    name: syncthing
    enabled: yes
    scope: user

- name: Setup fish shell  
  become_user: cake
  shell: 
    executable: /usr/bin/fish
    cmd: |
      curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
      fisher install PatrickF1/fzf.fish
  changed_when: False

