- block:
  - name: Lazygit cloning
    become_user: cake
    git:
      repo: https://github.com/jesseduffield/lazygit.git
      dest: /opt/lazygit/
      clone: yes
      update: yes
  - name: Lazygit installation
    become_user: cake
    command: go install
    args:
      chdir: /opt/lazygit
    register: result
    changed_when: result.stdout != ""

- name: Enable Syncthing
  become_user: cake
  systemd:
    name: syncthing
    enabled: yes
    scope: user

- name: Setup fish shell  
  become_user: cake
  shell: 
    executable: /usr/bin/fish
    cmd: |
      curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
      fisher install PatrickF1/fzf.fish
  changed_when: False
