- name: Add RPM Fusion repositories
  dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Add Docker repository
  shell: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
  changed_when: False

- name: Install fedora packages
  package:
    name:
      - alacritty
      - ansible
      - bat
      - bolt
      - brightnessctl
      - containerd.io # docker 
      - dconf-editor
      - docker-buildx-plugin 
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - docker-compose-plugin
      - fd-find
      - feh
      - ffmpeg
      - flatpak
      - flatseal
      - fzf
      - gvfs-fuse
      - gvfs-smb # thunar smb support
      - htop
      - jetbrains-mono-fonts-all
      - libva-utils
      - mpv
      - neovim
      - nodejs-bash-language-server
      - nodejs-typescript
      - prusa-slicer
      - qalculate
      - qalculate-qt
      - ripgrep
      - rofi
      - ShellCheck
      - synergy
      - tealdeer
      - telegram-desktop
      - unrar
      - util-linux-user # chsh command
      - wireguard-tools
      - wmctrl
      - x265
      - xdotool

- name: Remove unneeded default fedora packages
  package:
    state: absent
    name:
      - dnfdragora
      - dnfdragora-updater

- name: Add flathub remote for flatpak
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  flatpak:
    name:
      - com.bitwarden.desktop
      - com.discordapp.Discord
      - com.getmailspring.Mailspring 
      - com.google.Chrome
      - com.spotify.Client
      - com.teamspeak.TeamSpeak
      - md.obsidian.Obsidian 
      - net.hovancik.Stretchly
      - org.filezillaproject.Filezilla
      - org.libreoffice.LibreOffice 
      - org.signal.Signal

- name: Check if brew is already installed
  become_user: cake
  command: which brew
  register: brew_installed
  changed_when: brew_installed.stderr != ""
  ignore_errors: true

- name: Install brew
  become_user: cake
  shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_installed is failed

- name: Install brew packages
  become_user: cake
  homebrew:
    name:
      - chezmoi
      - golang
      - helix
      - lazydocker
      - lazygit
      - marksman # lsp markdown
      - yaml-language-server
      - zellij
