- name: Install flatpak packages
  flatpak:
    name:
      - bitwarden
      - com.discord
      - mailspring
      - md.obsidian
      - spotify
      - teamspeak

- name: Install fedora packages
  package:
    name:
      - ShellCheck
      - alacritty
      - ansible
      - bat
      - dconf-editor
      - fd-find
      - fzf
      - gnome-extensions-app
      - go
      - google-chrome-stable
      - jetbrains-mono-fonts-all
      - keybase
      - neovim
      - nodejs-typescript
      - prusa-slicer
      - qalculate
      - qalculate-qt
      - ripgrep
      - rofi
      - stow
      - synergy
      - tealdeer
      - telegram-desktop
      - wireguard-tools
      - wmctrl
      - xdotool
      - util-linux-user # chsh command

