- name: Add RPM Fusion repositories
  dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install flatpak packages
  flatpak:
    name:
      - bitwarden
      - com.discord
      - libreoffice
      - mailspring
      - md.obsidian
      - spotify
      - teamspeak

- name: Install fedora packages
  package:
    name:
      - ShellCheck
      - alacritty
      - ansible
      - bat
      - brightnessctl
      - dconf-editor
      - fd-find
      - firefox
      - fzf
      - gnome-extensions-app
      - go
      - google-chrome-stable
      - jetbrains-mono-fonts-all
      - neovim
      - nodejs-typescript
      - prusa-slicer
      - qalculate
      - qalculate-qt
      - ripgrep
      - rofi
      - synergy
      - tealdeer
      - telegram-desktop
      - util-linux-user # chsh command
      - wireguard-tools
      - wmctrl
      - xdotool

- name: Remove unneeded default fedora packages
  package:
    state: absent
    name:
      - dnfdragora
      - dnfdragora-updater
