- name: Add RPM Fusion repositories
  dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install fedora packages
  package:
    name:
      - ShellCheck
      - alacritty
      - ansible
      - bat
      - bolt
      - brightnessctl
      - chromium
      - dconf-editor
      - fd-find
      - firefox
      - flatpak
      - flatseal
      - fzf
      - gnome-extensions-app
      - go
      - gvfs-fuse
      - gvfs-smb # thunar smb support
      - htop
      - jetbrains-mono-fonts-all
      - mpv
      - neovim
      - nodejs-typescript
      - prusa-slicer
      - qalculate
      - qalculate-qt
      - ripgrep
      - rofi
      - synergy
      - tealdeer
      - telegram-desktop
      - unrar
      - util-linux-user # chsh command
      - wireguard-tools
      - wmctrl
      - xdotool

- name: Remove unneeded default fedora packages
  package:
    state: absent
    name:
      - dnfdragora
      - dnfdragora-updater

- name: Add flathub remote for flatpak
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  flatpak:
    name:
      - com.bitwarden.desktop
      - com.discordapp.Discord
      - org.filezillaproject.Filezilla
      - org.libreoffice.LibreOffice 
      - com.getmailspring.Mailspring 
      - md.obsidian.Obsidian 
      - org.signal.Signal
      - com.spotify.Client
      - net.hovancik.Stretchly
      - com.teamspeak.TeamSpeak
