- name: Install flatpak packages
  flatpak:
    name:
      - bitwarden
      - mailspring
      - md.obsidian
      - spotify
      - teamspeak

- name: Install fedora packages
  package:
    name:
      - alacritty
      - ansible
      - bat
      - code
      - dconf-editor
      - fd-find
      - fish
      - fzf
      - gnome-extensions-app
      - go
      - google-chrome-stable
      - jetbrains-mono-fonts-all
      - keybase
      - neovim
      - nodejs-typescript
      - qalculate
      - qalculate-qt
      - ripgrep
      - rofi
      - syncthing
      - synergy
      - tealdeer
      - telegram-desktop

- name: Install dependencies
  package:
    name:
      - gcc-c++ # LunarVim
      - nodejs-typescript # Pop Shell
      - python3-psutil # Ansible dconf module
      - util-linux-user # chsh command
      - xprop # Pop Shell

