- name: Install flatpak packages
  flatpak:
    name:
      - com.mongodb.Compass
      - com.slack.Slack
      - rest.insomnia.Insomnia

- name: Install brew packages
  become_user: cake
  homebrew:
    name:
      - azure/kubelogin/kubelogin
      - conftest
      - hashicorp/tap/vault
      - kubeconform
      - kubernetes-cli
      - kubeseal
      - marp-cli
      - metalbear-co/mirrord/mirrord
      - prometheus
      - yq
