---
# Install a font from a ZIP file
- name: Download and unzip font file
  ansible.builtin.unarchive:
    src: "{{ gnome_font.url }}"
    dest: "/tmp/"
    remote_src: yes
  become: yes
  changed_when: false

- name: Install font
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/share/fonts/
    remote_src: yes
  changed_when: false
  become: yes
  with_fileglob: "/tmp/{{ gnome_font.fonts|default([]) }}"
